# Generated by Django 5.2.8 on 2025-11-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subcategory_name',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tittle_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tittle_ru',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='udemy_app.subcategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='udemy_app.subcategory'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tittle_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='tittle_ru',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tittle_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tittle_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questions_name_en',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questions_name_ru',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questions_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questions_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
